import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const wubbaLubbaDubDub = localFont({
  src: [
    {
      path: "../../public/fonts/WubbaLubbaDubDub.ttf",
      weight: 700,
    },
  ],
  variant: "--font-weird",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${wubbaLubbaDubDub.variable}`}>
      <body className={inter.className`${wubbaLubbaDubDub.variable}`}>
        {children}
      </body>
    </html>
  );
}
